version: "3"

services:

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    container_name: loja_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lojavirtual
    ports:
      - "3306:3306"
    volumes:
      - mysql_db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: loja_phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  mysql_db:
